export const styles = {
  page: {
    fontFamily: "'Segoe UI', sans-serif",
    minHeight: "100vh",
    background: "#f0f2f5",
  } as React.CSSProperties,
  card: {
    background: "#fff",
    borderRadius: 12,
    padding: 24,
    boxShadow: "0 2px 8px rgba(0,0,0,.08)",
  } as React.CSSProperties,
  input: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid #d9d9d9",
    fontSize: 14,
    boxSizing: "border-box",
  } as React.CSSProperties,
  btn: {
    padding: "10px 20px",
    borderRadius: 8,
    border: "none",
    background: "#1677ff",
    color: "#fff",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
  } as React.CSSProperties,
  btnDanger: {
    padding: "8px 16px",
    borderRadius: 8,
    border: "none",
    background: "#ff4d4f",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  } as React.CSSProperties,
  label: {
    display: "block",
    marginBottom: 4,
    fontSize: 13,
    fontWeight: 600,
    color: "#333",
  } as React.CSSProperties,
  formGroup: { marginBottom: 16 } as React.CSSProperties,
  error: {
    background: "#fff1f0",
    border: "1px solid #ffccc7",
    borderRadius: 8,
    padding: "10px 14px",
    color: "#cf1322",
    marginBottom: 16,
    fontSize: 14,
  } as React.CSSProperties,
  success: {
    background: "#f6ffed",
    border: "1px solid #b7eb8f",
    borderRadius: 8,
    padding: "10px 14px",
    color: "#389e0d",
    marginBottom: 16,
    fontSize: 14,
  } as React.CSSProperties,
};
